apiVersion: v1
data:
  logstash.template.json: |-
      {
          "template": "logstash",
          "index_patterns": [
              "logstash-*"
          ],
          "settings": {
              "number_of_shards": 1
          },
          "mappings": {
              "properties": {
                  "name": {
                      "type": "keyword"
                  },
                  "class": {
                      "type": "keyword"
                  },
                  "state": {
                      "type": "integer"
                  },
                  "@timestamp": {
                      "type": "date"
                  }
              }
          }
      }


kind: ConfigMap
metadata:
  name: logstash-temp
  namespace: es-cluster
