## Node 1 As Master
apiVersion: v1
kind: Service
metadata:
  labels:
    app: es
  name: monitor
  namespace: es-cluster
spec:
  ports:
  - name: 9200-tcp
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: 9300-tcp
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
    deploymentconfig: monitor
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: es
  name: monitor
  namespace: es-cluster
spec:
  replicas: 1
  selector:
    app: es
    deploymentconfig: monitor
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: es
        deploymentconfig: monitor
    spec:
      containers:
      - env:
         - name: cluster.name
           value: 'monitor-cluster'
         - name: node.name
           value: 'monitor'
         - name: ES_JAVA_OPTS
           value: '-Xms512m -Xmx512m'
         - name: xpack.monitoring.collection.enabled
           value: 'false'
         - name: discovery.seed_hosts
           value: 'monitor'
         - name: cluster.initial_master_nodes
           value: 'monitor'
         - name: xpack.security.enabled
           value: 'true'
         - name: ELASTIC_PASSWORD
           value: 'abc123'
        image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
        imagePullPolicy: Always
        name: monitor
        ports:
        - containerPort: 9200
          protocol: TCP
        - containerPort: 9300
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: monitor
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: monitor
