apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch1
  namespace: es-cluster
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
  storageClassName: local-storage
