apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs1-pv
spec:
  storageClassName: nfs-direct
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/pv1
    server: 159.65.8.106
