apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: es
  name: nginx
  namespace: es-cluster
spec:
  replicas: 1
  selector:
    app: es
    deploymentconfig: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: es
        deploymentconfig: nginx
    spec:
      containers:
      - image: adisaputra10/bkn:php-7.4-nginx
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/www/html
          name: nginx
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: nginx
          persistentVolumeClaim:
             claimName: nfs-direct-pvc
