apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch1
  namespace: es-cluster
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/siasn-pgadmin
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: nodetype
          operator: In
          values:
          - pvc
