apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
  name: wordpress
  namespace: es-cluster
spec:
  ports:
  - name: 80-tcp
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    deploymentconfig: wordpress
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: es
  name: wordpress
  namespace: es-cluster
spec:
  replicas: 1
  selector:
    app: es
    deploymentconfig: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: es
        deploymentconfig: wordpress
    spec:
      containers:
      - image: wordpress:4.8-apache
        imagePullPolicy: Always
        name: wordpress
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/www/html
          name: wordpress
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: wordpress
        persistentVolumeClaim:
          claimName: wp-pv-claim
